spring:
  application:
    name: TaskManagementSystem

  datasource:
    url: jdbc:postgresql://192.168.77.138:5432/TaskManagementSystem
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  output:
    ansi:
      enabled: ALWAYS

  app:
    jwtSecret: WimJI26maddSDFHbegG1Qtl3gsC8BinoVBua6NNKU7ghh3qt8L0Egy6BpYysPlIamjZeRA
    jwtExpirationMs: 172800000









